export {Error} from './Error/Error';
export {Header} from './Header/Header';
export {Search} from './Header/Search/Search';
export {MovieCardHeader} from './MoviesCard/MovieCardHeader/MovieCardHeader';
export {Loader} from './Loader/Loader';
export {MovieList} from './MovieList/MovieList';
export {MoviesCard} from './MoviesCard/MoviesCard';
export {ErrorSearch} from './Error/ErrorSearch/ErrorSearch'
export {Main} from './Pages/Main'
export {InfoCardMovie} from './Pages/InfoCardMovie'
